## Summary script for week of 9/25/20.
import os
from script_doc_utils import initialize_doc,insert_image,get_relative_image_path

if __name__ == "__main__":
    md=initialize_doc({"next":"summary_week_10_9_20"})
    md.new_header(level = 1,title = "Work summary for week of of 9/25/20")
    md.new_line("This week, we piloted some ideas across different areas in the social behavior project.")
    md.new_paragraph("1) perhaps most notably, we are considering a "+ md.new_inline_link(link ="./polar_representation.md",text = "new representation") + " of the social behavior data in a hierarchical set of polar coordinates. Briefly, at the highest level, we represent the average position of all of the detected body parts. When we can think of this as representing the average motion of the two animalsover time. At the second level, we represent the positions of the mouse body parts as _deviations_ from the average position. This representation naturally clusters the body parts of the two animals, and opens the door to more robust body part and behavior detection methods. This representation also offers more straightforward ways to characterize the dynamics of pursuit events. It will be exciting to demonstrate the possibilities of this representation on groundtruth labeled pursuit event data. For more details and current work, see "+md.new_inline_link(link = "./polar_representation.md",text = "here."))
    md.new_paragraph("2) Regarding denoising, we have tested a new method for the detection of discontinuities, characteristic of switching errors. Currently our method for discontinuity detection relies upon heuristics with a set of cross-validated hyperparameters. This has been frustrating, because it makes it difficult to predict ahead of time the generalization of our approach across different pairs of animals, or even time scales, that we have not tested against. We are now considering discontinuity detection with wavelets through the Wavelet Transform Modulus Maxima (WTMM) method, where the problem is known as "+md.new_inline_link(link="./singularity_detection_example.md",text = "singularity detection") +". Notably, this method requires no parameters for the detection of potential discontinuities, beyond the discrete choice of a wavelet. It seems there are many potential applications of WTMM, such as in application to the new representation mentioned above in 1), but we need to do a little more work to be sure of its feasibility. A few potential applications include measuring the energy in the wavelet transform as a metric for branch and bound, or determining discontinuities in the data directly with WTMM-derived _structural_intensity_ maps, which represent the locations of discontinuities in the data as a probability distribution. Both these methods could be very useful to extend our analyses going forwards, to improve performance or get our results onto a more concrete basis than the foundations they have now. More generally, it seems that wavelet analyses have seen general use for trajectory classification in ecology, and these methods would be good to get a grasp on. In the future, we can also consider using wavelets transforms as an independet measure of the synchrony between the two animals, which could be useful for pursuit/interaction analysis (see Polansky et al. 2010, Maraun et al. 2008). For more details and current work, see "+md.new_inline_link(link = "./singularity_detection_example.md", text = "here.")) 
    md.new_paragraph("3) As a smaller, conceptual point, in the course of researching these approaches, I found several papers (Faloustos et al. 1994, Sharifzadeh et al. 2005) that frame the algorithms that they propose as queries to a spatio-temporal database. This may not be a framework we need, but it has influenced the way I think about polar representations, and the importance of representing data in a semantically meaningful way. This might be useful for stories that we want to tell later on.")
    md.new_line("This pilot experience sets up our game plan for the next few weeks:")
    todolist = [
            "Polar Data Representation",
            [
                "Render all existing data in 2-level polar representation",
                "Test 3-level representation with per-mouse average level included",
                "Build in mouse-specific data into representation with marked training points",
                "Determine robustness vs. existing methods for pursuit detection",
                ],
            "Denoising Revisited",
            [
                "Classify trajectories based on 1) existence of switches, and 2) entire loss of other animal with clustering algorithms on relative bodypart angle.",
                "Segment with clustering algorithms on the angles of body parts",
                "Compare to segmentation generated by current heuristic measures."
                "Try Branch and Bound with Wavelet Transform/ WTMM. (This is a good cost because linear interpolation will be interpreted as a singularity too).",
                "Compare to current segment assignment formalism"
                ],
            "Pursuit Characterization",
            [
                "Characterize stereotypy in groundtruth pursuits with polar representation",
                [
                    "Cluster average position signal (l1, theta1)",
                    "Cluster relative position signal (l2, theta2)"
                    ],
                "Detect stereotypical pre-pursuit events: 'turning' about the mean position."
                "Look for interesting stereotypy characteristics across non-pursuit portions of the trajectory."
                ],
            ]
    md.new_checkbox_list(todolist)
    md.new_line("For next week, I will focus on the first two items of Polar Data representation and the first three items of Denoising Revisited.")
    
    
    md.create_md_file()
